- src/picture.rs
With this patch, when MIME type is `image/jpg`, Lofty will recognize it as `MimeType::Jpeg` too, instead of falling back to `Unknown`.
I tested this patch with [Amberol](https://gitlab.gnome.org/World/amberol) (Which uses [MimeType::](https://gitlab.gnome.org/World/amberol/-/blob/3ea0b2e40c3c2fff8593b04b08ad54de8076639f/src/audio/song.rs#L84-86) enums to decide whether to show album arts) and now it displays JPG album arts just fine.
In my opinion, I don't see a reason for creating a `MimeType::Jpg` enum, since actually JPG and JPEG are the same thing but with a different extension.
> Recognize `image/jpg` as `MimeType::Jpeg`

- src/tag/item.rs
Hi there, I noticed a potential typo in the key used for `InitialKey`. According to the [id3v2.4](https://id3.org/id3v2.4.0-frames) spec, the frame for the initial key should be called `TKEY`, not `TLEY`.
Really enjoying using this crate, thank you!
> Fix typo in `InitialKey` key

- src/mpeg/header.rs
Some MP3 files have garbage before the MPEG frames. Lofty tries to skip them by looking for sync bits, reading a header, seeking to the next one and comparing that to the first header. This works fine most of the time.
The issue I had was that in a few MP3 files, I had garbage that contained long strings of `ff` bytes. A header `ff ff ff ff` has invalid bitrate and frequency (sample rate) but would be returned from `Header::read` as if it was valid -- the Header struct would be half-zeroed though. The frame length (`len`) is also zero, so for validation in `find_next_frame` the next 4 bytes would be read. If those happen to also be `ff ff ff ff`, it passes validation. The whole file is later determined to be invalid in `read_from`, which does check the sample rate.
I found this issue when …
> MP3: Improve validation of frame headers

- src/id3/v2/frame/content.rs
- src/id3/v2/frame/mod.rs
- src/id3/v2/items/popularimeter.rs
- src/id3/v2/tag.rs
Use the `rating` field as the value of the Popularimeter tags when handling ID3v2 tags.
closes #63
> ID3v2: populate popularimeter tag from frame value

- CHANGELOG.md
- Cargo.toml
- lofty_attr/src/lofty_file.rs
- src/file.rs
Previously, we just removed and dropped the tag. That should really be left up to the user, though.
> lofty_attr: Return removed tags in <File>::remove_*

- CHANGELOG.md
- Cargo.toml
- ogg_pager/src/error.rs
- ogg_pager/src/header.rs
- ogg_pager/src/lib.rs
- src/ogg/mod.rs
- src/ogg/opus/mod.rs
- src/ogg/opus/properties.rs
- src/ogg/read.rs
- src/ogg/speex/mod.rs
- src/ogg/speex/properties.rs
- src/ogg/vorbis/mod.rs
- src/ogg/vorbis/properties.rs
- src/ogg/vorbis/write.rs
- src/ogg/write.rs
- src/resolve.rs
This makes the handling of OGG files a lot more spec-compliant, and simpler overall.
> OGG: Switch to using packets instead of individual pages

- CHANGELOG.md
- examples/tag_reader.rs
- examples/tag_stripper.rs
- examples/tag_writer.rs
- lofty_attr/src/lofty_file.rs
- src/file.rs
- src/lib.rs
- src/resolve.rs
- tests/files/aac.rs
- tests/files/aiff.rs
- tests/files/ape.rs
- tests/files/mp4.rs
- tests/files/mpeg.rs
- tests/files/ogg.rs
- tests/files/wav.rs
- tests/files/wavpack.rs
> files: Implement BoundTaggedFile

- src/mp4/atom_info.rs
- src/mp4/ilst/atom.rs
- src/mp4/ilst/mod.rs
- src/mp4/ilst/ref.rs
- src/mp4/ilst/write.rs
Otherwise you would need to use `once_cell` for constants. This extension by using `Cow` also makes `AtomIdentRef` obsolete.
> Allow to create AtomIdent constants with 'static lifetime

- CHANGELOG.md
- src/tag/item.rs
This atom is only contained in files bought from the iTunes store, but very common for MP4 files and it contains valuable information.
The format and contents are defined in the development guide: https://www.apple.com/nz/itunes/lp-and-extras/docs/Development_Guide.pdf
> mp4: Add new item key AppleXID

- src/mp4/ilst/mod.rs
This is consistent with other tag types.
> mp4: Map FlagCompilation to text "0"/"1" 

- src/id3/v2/frame/header.rs
- src/id3/v2/frame/id.rs
- src/id3/v2/frame/mod.rs
- src/id3/v2/frame/read.rs
- src/id3/v2/tag.rs
- tests/tags/conversions.rs
The next step towards more efficient memory management. Most of the predefined string constants have a `'static` lifetime.
> Reduce memory allocations for id3v2::FrameID

- src/id3/v2/frame/mod.rs
- src/id3/v2/tag.rs
See my comment directly in the code.
> id3v2: Use "XXX" if the actual language is unknown

- src/tag/item.rs
See also #113.
Writing tags cannot be accomplished with purely generic code. It requires pre/post-processing depending on the type of the tag.
> mp4: Write integer bpm

- src/tag/item.rs
As discussed in #113 we can only disambiguate and not resolve this issue. Applications have to deal with that.
Note: Will cause a minor merge conflict with #117.
> Disambiguate ID3v2 TIT1/GRP1

- src/mp4/ilst/atom.rs
- src/mp4/ilst/mod.rs
See the code comments and links for further information.
> mp4: More robust parsing and updated mapping of `rtng` atom

- src/id3/v2/tag.rs
Needed for synchronization when writing tags. Especially for preserving frames that cannot be mapped to `TagItem`s.
> id3v2: Retain frames by predicate

- src/id3/v2/frame/id.rs
- src/mp4/atom_info.rs
- src/mp4/ilst/atom.rs
These were missing or inconsistent and are needed by clients.
> Add conversions between borrowed/owned data

- src/id3/v2/frame/mod.rs
- src/id3/v2/tag.rs
Plain comments are supposed to have an empty description aka *content descriptor*. Only those must appear as `ItemKey::Comment`, otherwise this would cause confusion and inconsistencies during the read/write round trip.
> id3v2: Distinguish COMM frames by content descriptor

- src/ape/tag/mod.rs
- src/id3/v1/tag.rs
- src/id3/v2/tag.rs
- src/iff/aiff/tag.rs
- src/iff/wav/tag/mod.rs
- src/lib.rs
- src/mp4/ilst/atom.rs
- src/mp4/ilst/mod.rs
- src/ogg/tag.rs
- src/picture.rs
- src/tag/mod.rs
- src/traits.rs
Adds a new trait `SplitAndRejoinTag` with methods that are needed for safely and efficiently implementing read/modify/write round trips when synchronizing metadata:
- `fn split_tag(&mut self) -> Tag;`
- `fn rejoin_tag(&mut self);`
The central function from my code base that accomplishes the task demonstrates how they are supposed to be used:
```rust
fn split_export_rejoin_track_to_tag<T>(
tag_repr: &mut T,
config: &ExportTrackConfig,
track: &mut Track,
edit_embedded_artwork_image: Option<EditEmbeddedArtworkImage>,
) where
T: SplitAndRejoinTag,
{
// Split the generic tag contents from the underlying representation.
// The remainder will remain untouched while modifying the generic tag.
let mut tag = tag_repr.split_tag();
// Export the metadata of the given track into the generic tag, i.e. …
```
> Split and rejoin tags for read/modify/write round trips

- .github/workflows/ci.yml
- Cargo.toml
- ogg_pager/src/header.rs
- ogg_pager/src/lib.rs
- ogg_pager/src/packets.rs
- ogg_pager/src/paginate.rs
- src/id3/v2/tag.rs
- src/ogg/mod.rs
- src/ogg/opus/mod.rs
- src/ogg/opus/properties.rs
- src/ogg/read.rs
- src/ogg/speex/mod.rs
- src/ogg/speex/properties.rs
- src/ogg/tag.rs
- src/ogg/vorbis/mod.rs
- src/ogg/vorbis/properties.rs
- src/ogg/write.rs
- src/tag/mod.rs
> OGG: Properly handle large packets

- Cargo.toml
- src/macros.rs
> Remove cfg-if dependency

- src/id3/v2/tag.rs
- src/mp4/ilst/mod.rs
- src/ogg/tag.rs
- src/traits.rs
The support for multi-valued items in ID3v2 tags was very limited as I noticed while fixing an issue in the context of #103:
- Extend support for multi-valued field in ID3v2 tags, i.e. not only `TrackArtist`.
- Warn when replacing and dropping multi-valued items in ID3v2 tags unintentionally.
- Add tests for conversion round trips with multi-valued items.
This is probably not the most elegant solution, but at least a start accompanied by tests.
> id3v2/mp4/ogg: Add tests for multi-valued item conversion

- src/tag/mod.rs
> OGG: Verify opus-tools is available before running test

- src/ogg/tag.rs
- src/tag/item.rs
Fixes #90 so that we don't need to keep that issue around.
> Vorbis: Add mapping for InitialKey

- .github/dependabot.yml
- .github/workflows/bench.yml
- .github/workflows/ci.yml
https://github.com/actions-rs/cargo is unmaintained.
> GitHub CI: Replace actions-rs with dtolnay/rust-toolchain

- src/id3/v2/frame/mod.rs
- src/id3/v2/tag.rs
- tests/files/mpeg.rs
> ID3v2: Fix about number pair of track and disk

- src/aac/properties.rs
- src/ape/properties.rs
- src/flac/properties.rs
- src/iff/aiff/properties.rs
- src/iff/wav/properties.rs
- src/lib.rs
- src/mp4/properties.rs
- src/mpeg/properties.rs
- src/ogg/opus/properties.rs
- src/ogg/speex/properties.rs
- src/ogg/vorbis/properties.rs
- src/properties.rs
- src/wavpack/properties.rs
Currently only supported by WAV files.
- The `ChannelMask` newtype cannot be constructed, i.e. read-only. Edit: Only the `mono()` and `stereo()` constructors are public for convenience and also serve as examples.
- Implementation detail: Explicit destructuring of format-specific file properties upon conversion is safer when new fields are added in the future.
> Expose channel mask in file properties

- CHANGELOG.md
- src/ape/tag/mod.rs
- src/id3/v1/tag.rs
- src/id3/v2/tag.rs
- src/iff/aiff/tag.rs
- src/iff/wav/tag/mod.rs
- src/lib.rs
- src/mp4/ilst/mod.rs
- src/ogg/tag.rs
- src/tag/mod.rs
- src/traits.rs
This is the follow-up for #137 to avoid unexpected/undefined behavior at runtime.
Finally, the typestate pattern is in place. Separation into 2 traits was the missing link.
> v0.12.0: Separate SplitAndMergeTag into SplitTag/MergeTag for compile-time safety

- src/id3/v2/frame/content.rs
- src/id3/v2/frame/mod.rs
- src/id3/v2/items/identifier.rs
- src/id3/v2/items/mod.rs
- src/id3/v2/tag.rs
- src/id3/v2/write/frame.rs
> ID3v2: Add support for MusicBrainzRecordingId

- src/picture.rs
This adds some functions that exposes the inner data.
Since the inner `Cow` is `Cow::Owned`, `into_owned()` _should_ be a cheap no-clone/no-allocation call.
Also, most libraries seem use `bytes()` or `as_bytes()` instead of `data()` but that'll break everyone's code, so, maybe not worth it.
> picture: add `into_data()`

- src/tag/item.rs
- src/tag/mod.rs
Successor for #180. The method `Tag::remove_empty()` is not strictly necessary, but probably convenient.
> tag: Check for and remove empty item values

- src/id3/v2/frame/content.rs
- src/id3/v2/frame/mod.rs
- src/id3/v2/frame/read.rs
- src/id3/v2/items/attached_picture_frame.rs
- src/id3/v2/items/extended_text_frame.rs
- src/id3/v2/items/extended_url_frame.rs
- src/id3/v2/items/identifier.rs
- src/id3/v2/items/language_frame.rs
- src/id3/v2/items/popularimeter.rs
- src/id3/v2/items/text_information_frame.rs
- src/id3/v2/items/url_link_frame.rs
- src/id3/v2/mod.rs
- src/id3/v2/read.rs
- src/id3/v2/util/synchsafe.rs
- src/util/text.rs
- tests/picture/format_parsers.rs
Previously, we would immediately read the entire tag into memory as well as each frame's content. Now, we only allocate when necessary, reusing the original reader.
> ID3v2: Remove unnecessary allocations

- src/id3/v2/items/audio_text_frame.rs
According to https://mutagen-specs.readthedocs.io/en/latest/id3/id3v2-accessibility-1.0.html#proposed-audio-text-frame:
"More than one audio-text frame may be present in a tag but each must carry a unique string in the Equivalent text field."
> ID3v2: Correct equality/hash impl for `AudioTextFrame`

- CHANGELOG.md
- src/mp4/ilst/read.rs
In the event that the `plID` atom has the wrong code (which seems to be the case quite often), we wouldn't populate the atom data properly. This would lead to a panic when converting to `Tag`.
This removes the code check entirely, since we can no longer trust that to be correct. We also now verify that there's *something* present.
closes #201
> MP4: Fix parsing of plID atoms with incorrect codes

- CHANGELOG.md
- src/aac/read.rs
- src/ape/read.rs
- src/flac/read.rs
- src/id3/v2/frame/content.rs
- src/id3/v2/frame/read.rs
- src/id3/v2/items/identifier.rs
- src/id3/v2/read.rs
- src/id3/v2/tag.rs
- src/iff/aiff/read.rs
- src/iff/chunk.rs
- src/iff/wav/read.rs
- src/macros.rs
- src/mpeg/read.rs
- src/ogg/opus/mod.rs
- src/ogg/read.rs
- src/ogg/speex/mod.rs
- src/ogg/tag.rs
- src/ogg/vorbis/mod.rs
- src/probe.rs
The new `BestAttempt` variant will be less eager to error than the previous default, `ParsingMode::Strict`. This comes with the consequence that the input may not be *entirely* spec-compliant.
This implements `BestAttempt` for `UniqueFileIdentifierFrame::parse` and adds `Strict` checks for `VorbisComments` parsing. More checks will come in the future.
closes #204
> probe: Add new default ParsingMode variant

- CHANGELOG.md
- src/macros.rs
- src/util/alloc.rs
- src/util/mod.rs
This adds an arbitrary allocation limit of 8MB for any one item, which should be more than enough in any case.
This was changed to stop the fuzz tests from failing with OOM errors.
> misc: Add allocation limit to `try_vec!`

- src/error.rs
- src/id3/v2/frame/header.rs
- src/id3/v2/frame/id.rs
- src/id3/v2/frame/mod.rs
- src/id3/v2/tag.rs
This is the first step to reveal information about malformed/unsupported tags.
Those frames should be skipped when parsing in `Relaxed` mode.
Note: The `BadFrameId` error was used for different purposes, not only for parsing as the message suggests.
> ID3v2: Report bad or unsupported frame IDs

- CHANGELOG.md
- Cargo.toml
- lofty_attr/src/internal.rs
- src/ape/tag/mod.rs
- src/ape/tag/write.rs
- src/id3/v2/tag.rs
- src/id3/v2/util/mod.rs
- src/id3/v2/util/pairs.rs
- src/tag/item.rs
- src/tag/utils.rs
This also changes the default track/disk number to `DEFAULT_NUMBER_IN_PAIR`.
closes #159
> APE: Properly convert track/disk number pairs when writing

- CHANGELOG.md
- src/flac/read.rs
- src/ogg/read.rs
- src/ogg/tag.rs
- src/ogg/write.rs
* Stop ignoring fields whose size fails the `u32` -> `usize` conversion, now throwing `TooMuchData`
* Stop requiring `&mut VorbisComments` to be passed to `read_comments`
* Remove intermediary String creation in `read_comments` (Now only allocating once, until all information is verified)
* Start logging more warnings when data is being discarded
> OGG: Cleanup and fixes

- CHANGELOG.md
- src/properties.rs
- src/wavpack/properties.rs
This also fixes metadata sub block reading as a result.
Also took the opportunity to read the channel mask out of the `MULTICHANNEL` metadata sub block, which was previously skipped.
> WavPack: Fix multichannel detection

- CHANGELOG.md
- src/id3/v2/tag.rs
This adds `Id3v2Tag::{get, insert}_user_text` to simplify the process of working with TXXX frames with their descriptions.
> ID3v2: Add simplified getters and setters for TXXX frames

- CHANGELOG.md
- src/id3/v2/frame/id.rs
- src/id3/v2/tag.rs
This changes two things:
1. `FrameId` now implements `Into<Cow<'_, str>>`
This makes it possible to use `FrameId`s in `Frame::new`. It's now much less annoying to create frames using constant IDs.
2. `Id3v2Tag::remove` now takes a `FrameId`
This makes it more type safe and removes the unnecessary caseless string comparison.
> ID3v2: Make FrameId less annoying

- src/tag/item.rs
I forgot about that this was already implemented.
> id3v2: Add comment about handling of MusicBrainzRecordingId

- CHANGELOG.md
- src/error.rs
- src/mp4/ilst/atom.rs
- src/mp4/ilst/mod.rs
* `Ilst::insert_picture` will now combine pictures into a single `covr` atom
* `Atom::merge` for combining the data of two atoms
* `Atom::into_data` to consume an `Atom` and return its data
* `Ilst::remove` will now return all removed atoms
* `Ilst::pictures` will now only check for a single `covr` atom
* `Ilst::insert` will now merge with existing atoms
* Now, when inserting an atom that already exists in a tag, the data is taken from the provided atom and merged with the existing value in the tag. This should ensure that the value that already exists in the tag will remain the dominant one.
> MP4: Correctness fixes

- CHANGELOG.md
- src/wavpack/properties.rs
When a custom sample rate (or multiplier) was encountered, it would accidentally be overwritten with 0, causing incorrect duration and bitrate values.
This was due to us reading the metadata sub blocks first (when necessary) and then immediately overwriting the sample rate with the value from the block header (which is 0 in the presence of a custom sample rate).
> WavPack: Stop overwriting custom sample rates

- CHANGELOG.md
- src/ape/properties.rs
- src/ape/read.rs
- src/lib.rs
- src/properties.rs
- tests/files/zero_sized.rs
This also makes property reading take `ParsingMode` into account.
> APE: Fix property reading on old stream versions

- CHANGELOG.md
- fuzz/fuzz_targets/picture_from_flac_bytes.rs
- src/flac/read.rs
- src/lib.rs
- src/ogg/read.rs
- src/picture.rs
- tests/picture/format_parsers.rs
* We now support reading COVERART fields, which will be upgraded to METADATA_BLOCK_PICTURE on write.
* FLAC picture blocks can have any picture type now, and it will simply max out at 255.
closes #253
> OGG: Support reading COVERART fields/Make FLAC pictures less strict

- CHANGELOG.md
- src/id3/v2/frame/id.rs
- src/id3/v2/tag.rs
- tests/files/mpeg.rs
- tests/tags/conversions.rs
For consistency since `&str` is no longer used for frame creation and removal.
> ID3v2: Use FrameId for Id3v2Tag getters

- src/mp4/ilst/mod.rs
- src/mp4/ilst/read.rs
- src/mp4/moov.rs
- src/mp4/read.rs
Make use of `ParsingMode` and ignore invalid/unexpected `ilst` atoms that could safely be ignored.
I found a few affected files that are accepted by other MP4 parsers.
PS: It would be cool to include this in a v0.16.1 release soon.
> mp4: Skip unexpected or empty "data" ilst atoms

- CHANGELOG.md
- src/mp4/ilst/mod.rs
These came awhile before the `Accessor` methods, and managed to stick around for almost a year and a half after the fact. :smile:
> MP4: Remove duplicate track/disc methods on `Ilst`

- CHANGELOG.md
- src/id3/mod.rs
Unfortunately, this isn't the only place we do unchecked seeks.
An error is rarely (if ever) going to appear from them, since we're talking about incredibly tiny inputs. Doesn't mean it can be entirely ignored, though.
> ID3v1: Stop erroring on inputs smaller than 128 bytes

- src/ape/tag/mod.rs
- src/id3/v1/tag.rs
- src/id3/v2/tag.rs
- src/iff/aiff/tag.rs
- src/iff/wav/tag/mod.rs
- src/ogg/tag.rs
Skimming the docs I found that the descriptions of what to expect when converting to/from `Tag` were either missing or just made no sense. Hopefully the situation is a little better now.
> Improve `Tag` conversion docs

- CHANGELOG.md
- src/ogg/tag.rs
Turns out we were just blindly taking any key during the `Tag` -> `VorbisComments` conversion
> VorbisComments: Check `ItemKey::Unknown` for spec compliance

- fuzz/fuzz_targets/aacfile_read_from.rs
- fuzz/fuzz_targets/aifffile_read_from.rs
- fuzz/fuzz_targets/apefile_read_from.rs
- fuzz/fuzz_targets/flacfile_read_from.rs
- fuzz/fuzz_targets/mp4file_read_from.rs
- fuzz/fuzz_targets/mpegfile_read_from.rs
- fuzz/fuzz_targets/opusfile_read_from.rs
- fuzz/fuzz_targets/speexfile_read_from.rs
- fuzz/fuzz_targets/vorbisfile_read_from.rs
- fuzz/fuzz_targets/wavfile_read_from.rs
- fuzz/fuzz_targets/wavpackfile_read_from.rs
No idea why all of the targets had `read_properties(false)`.
> Fuzz: Read properties in file read targets

- src/ape/tag/read.rs
- src/error.rs
- src/id3/v2/items/extended_text_frame.rs
- src/id3/v2/items/extended_url_frame.rs
- src/id3/v2/items/language_frame.rs
- src/id3/v2/items/ownership_frame.rs
- src/id3/v2/items/sync_text.rs
- src/id3/v2/items/text_information_frame.rs
- src/iff/aiff/properties.rs
- src/iff/chunk.rs
- src/mp4/ilst/read.rs
- src/ogg/read.rs
- src/picture.rs
- src/util/text.rs
This should fix most issues when decoding text with trailing null characters.
Optionally, you could pass `ParsingMode` to the text decode functions and only apply the trimming if non-strict parsing is requested.
> Strip trailing null characters from decoded text

- CHANGELOG.md
- src/id3/v2/items/extended_text_frame.rs
- src/util/text.rs
> ID3v2: Properly handle multi-value UTF-16 encoded frames

- CHANGELOG.md
- src/id3/v2/tag.rs
I played around with this and came up with an implementation that returns an iterator and avoids allocation. It seemed appropriate to change the genre getter for the `Accessor` impl to use the new method so that numeric IDs will be translated and multiple values joined with '/' as per `get_text`. That's done as a separate commit in case it's a problem.
One question is whether `get_texts` and `get_text` should behave the same as `genres` and `genre` for TCON frames? I think this could be done fairly cleanly by reworking `GenresIter` into a more generic `MultiValueIter` and using it in `get_texts`. I can add another commit to this PR to address that if necessary.
closes #281
> ID3v2: Handle genre IDs in TCON frames

- CHANGELOG.md
- src/mp4/properties.rs
- src/properties.rs
This also has the side effect of making us now read every sample entry, which means we can now skip unknown entries to potentially find a suitable one.
Credit to `Lukáš Lalinský` for finding the location of the undocumented `drms` atom.
Source: <https://mail.kde.org/pipermail/taglib-devel/2011-March/001886.html>
> MP4: Check if audio streams are DRM protected

- CHANGELOG.md
- src/lib.rs
- src/math.rs
- src/mp4/properties.rs
- src/properties.rs
* We used to not read the `dfLa` atom containing FLAC stream information, due to the wrong FOURCC being checked
* Duration millisecond counts would sometimes be off by one. We now round, which should be done in other places.
> MP4 property fixups

- src/iff/wav/properties.rs
This caused a panic when trying to probe a >60min .wav set of me.
> [wav] Fix u32 overflow by first casting stream_len to u64 before multiplying

- CHANGELOG.md
- benches/create_tag.rs
- src/id3/v2/items/attached_picture_frame.rs
- src/id3/v2/restrictions.rs
- src/id3/v2/tag.rs
- src/mp4/ilst/mod.rs
- src/mp4/ilst/read.rs
- src/mp4/ilst/write.rs
- src/mpeg/header.rs
- src/mpeg/properties.rs
- src/ogg/picture_storage.rs
- src/ogg/read.rs
- src/picture.rs
- src/properties.rs
- src/tag/mod.rs
- tests/picture/from_reader.rs
This removes:
* `MimeType::None`
* `TextSizeRestrictions::None`
* `ImageSizeRestrictions::None`
* `Emphasis::None`
Instead of `X::None`, it's clearer to just store an `Option<X>`.
> Remove `None` variants on multiple enums

- Cargo.toml
- src/ogg/read.rs
- src/picture.rs
More versatile, easy to use, smaller, well-maintained.
> Replace base64 with data-encoding

- CHANGELOG.md
- src/id3/v2/items/attached_picture_frame.rs
- src/id3/v2/items/audio_text_frame.rs
- src/id3/v2/items/encapsulated_object.rs
- src/id3/v2/items/extended_text_frame.rs
- src/id3/v2/items/extended_url_frame.rs
- src/id3/v2/items/key_value_frame.rs
- src/id3/v2/items/language_frame.rs
- src/id3/v2/items/ownership_frame.rs
- src/id3/v2/items/popularimeter.rs
- src/id3/v2/items/private_frame.rs
- src/id3/v2/items/relative_volume_adjustment_frame.rs
- src/id3/v2/items/sync_text.rs
- src/id3/v2/items/text_information_frame.rs
- src/id3/v2/items/unique_file_identifier.rs
- src/id3/v2/items/url_link_frame.rs
- src/id3/v2/tag.rs
- src/util/text.rs
This changes the signature of `decode_text` to take the new `TextDecodeOptions`. This allows us to specify a UTF-16 BOM ahead of time.
closes https://github.com/Serial-ATA/lofty-rs/issues/306
> ID3v2: Support UTF-16 TIPL frames with single BOM

- src/ogg/opus/properties.rs
- src/ogg/speex/properties.rs
- src/ogg/vorbis/properties.rs
- src/properties.rs
This brings us to parity with FFmpeg durations.
> OGG: Use rounded division to calculate durations

- CHANGELOG.md
- src/mp4/atom_info.rs
- src/mp4/ilst/write.rs
- src/mp4/mod.rs
- src/mp4/read.rs
- src/mp4/write.rs
Previously the offset atoms remained untouched, which would point audio players to the wrong spot, leading them to believe the file was corrupted.
closes #308
> MP4: Update offset atoms on write

- CHANGELOG.md
- src/ape/read.rs
- src/file.rs
- src/id3/v2/frame/header.rs
- src/id3/v2/frame/read.rs
- src/id3/v2/write/mod.rs
- src/mpeg/read.rs
- src/probe.rs
Now when we can't find an ID3v2 tag at the start of the file, we search the area between the start and the first MPEG frame (or just `max_junk_bytes`, whichever is smaller).
For now, this is only done for MPEG files, and ID3v2 tags. APE header tags are less important, so similar functionality can be implemented later.
> MPEG: Find ID3v2 tags buried in junk

- CHANGELOG.md
- examples/custom_resolver/src/main.rs
- src/file.rs
- src/global_options.rs
- src/lib.rs
- src/probe.rs
- src/resolve.rs
- src/util/alloc.rs
This moves `ParseOptions::{use_custom_resolvers, allocation_limit}` to the new `GlobalOptions` struct. This makes it easier to check for certain options in places where `ParseOptions` may not be available.
`GlobalOptions` are not truly global, they only apply to the current thread.
> Probe: Introduce `GlobalOptions` to handle allocations and resolvers

- src/tag/item.rs
> mp4: Map "----:com.apple.iTunes:ORIGINALDATE" to OriginalReleaseDate

- CHANGELOG.md
- src/id3/v2/tag.rs
Convenient null separator handling is now exclusively done for `Accessor` methods. For all other use cases, the caller is given the raw string, with separators intact.
> ID3v2: Stop editing the string in Id3v2Tag::get_text()

- src/tag/item.rs
> ItemKey: Distinguish between Bpm and IntegerBpm

- src/mp4/ilst/mod.rs
- src/tag/mod.rs
A cast was missing.
I also changed the default value to 0 consistently for both current/total numbers and consider 0 as invalid/missing.
All these setters/getters are obviously untested.
> mp4: Fix conversion of u16 track/disc numbers to BE bytes

- src/id3/v2/items/extended_text_frame.rs
- src/id3/v2/items/sync_text.rs
- src/id3/v2/tag/tests.rs
- src/util/text.rs
Fixes one of the panics discovered in #295.
> id3v2: Fix parsing of UTF-16 when BOM is missing

- src/id3/v2/frame/mod.rs
- src/id3/v2/read.rs
I have found an MP3 file with 2 comment frames. The first frame contains the actual value and the second frame is empty.
Quod Libet and mediainfo only show the first comment, while exiftool and lofty pick the second, empty comment. Many applications like Mixxx also only read the first non-empty frame and ignore any subsequent, empty frames. Even though TagLib provides access to all of them.
This fix tries to avoid loss of information and behaves like most other applications would handle those conflicts.
> id3v2: Do not replace non-empty frames with duplicate, empty frames

- src/ape/properties.rs
- src/ape/tag/item.rs
- src/ape/tag/mod.rs
- src/file.rs
- src/id3/v2/frame/mod.rs
- src/id3/v2/tag.rs
- src/iff/aiff/tag.rs
- src/ogg/write.rs
- src/util/text.rs
Apparently these traits are in the prelude now.
> misc: Remove redundant Try{From, Into} imports

- lofty_attr/src/attribute.rs
To silence an annoying Clippy error.
> lofty_attr: Allow dead code

- src/traits.rs
Somehow some extra slashes ended up in the getter examples.
> Accessor: Remove slashes in example

- src/ape/read.rs
- src/ape/tag/write.rs
- src/flac/read.rs
- src/id3/mod.rs
- src/id3/v2/write/mod.rs
- src/mpeg/read.rs
- src/musepack/read.rs
This moves the existing search through junk from MPEG into `find_id3v2()`, so that other formats can potentially take advantage of it.
> ID3: Search through junk in `find_id3v2()`

- src/wavpack/properties.rs
WavPack supports unknown sample counts:
```c
typedef struct {
// ...
uint32_t total_samples;     // total samples for entire file, but this is
// only valid if block_index == 0 and a value of
// -1 indicates unknown length
// ...
} WavpackHeader;
```
(https://web.archive.org/web/20150424062034/https://www.wavpack.com/file_format.txt)
This wasn't checked for before, so it would produce wild results for the duration. I don't plan on actually fixing this anytime soon, I'd just rather produce no results than wrong results.
> WavPack: Add a TODO for unknown sample counts

- CHANGELOG.md
- src/probe.rs
This was copied from some other struct when `ParseOptions` was made. It obviously should not exist.
> ParseOptions: Stop deriving Ord

- .github/workflows/bench.yml
- Cargo.toml
- benches/create_tag.rs
- benches/read_file.rs
* `iai_callgrind` will make CI benchmarking actually make sense
* [`Bencher`](https://bencher.dev) supports `iai_callgrind` output, unlike `github-action-benchmark`
> benches: Switch to iai_callgrind + Bencher

- CHANGELOG.md
- src/properties.rs
This also adds associated constants for common channels.
> ChannelMask: Implement `Bit{Or,And}`

- CHANGELOG.md
- benches/create_tag.rs
- src/file/file_type.rs
- src/iff/aiff/mod.rs
- src/iff/aiff/read.rs
- src/iff/aiff/tag.rs
- src/iff/wav/mod.rs
- src/iff/wav/read.rs
- src/iff/wav/tag/mod.rs
- src/iff/wav/tag/read.rs
- src/tag/split_merge_tag.rs
- src/tag/tag_ext.rs
Turns out these two weren't renamed back in 0.13.0
> iff: Rename IFF tags

- CHANGELOG.md
- lofty/src/id3/v2/tag.rs
- lofty/src/id3/v2/tag/tests.rs
- lofty/src/mp4/ilst/mod.rs
- lofty/src/tag/item.rs
> Tag: Support `ItemKey::ParentalAdvisory` for Ilst and ID3v2

- CHANGELOG.md
- lofty/Cargo.toml
- lofty/src/config/global_options.rs
- lofty/src/id3/v2/tag.rs
- lofty/src/id3/v2/tag/tests.rs
- lofty/src/id3/v2/write/frame.rs
- lofty/src/id3/v2/write/mod.rs
- lofty/src/mp4/ilst/mod.rs
- lofty/src/tag/companion_tag.rs
- lofty/src/tag/mod.rs
- lofty/src/tag/utils.rs
- lofty_attr/src/internal.rs
> GlobalOptions: Add `preserve_format_specific_items()`

- CHANGELOG.md
- lofty/src/id3/v2/frame/conversion.rs
- lofty/src/id3/v2/frame/mod.rs
- lofty/src/id3/v2/items/language_frame.rs
- lofty/src/id3/v2/tag.rs
- lofty/src/id3/v2/tag/tests.rs
- lofty/src/tag/item.rs
- lofty/src/tag/items/lang.rs
- lofty/src/tag/items/mod.rs
- lofty/tests/tags/conversions.rs
`TagItem` can now store a language and description, making it possible to convert all ID3v2 `COMM` and `USLT` frames to their generic `ItemKey::{Comment, Lyrics}` counterparts.
fixes #383
> ID3v2: Allow for generic conversion of language frames

- lofty/src/id3/v2/items/attached_picture_frame.rs
- lofty/src/id3/v2/items/audio_text_frame.rs
- lofty/src/id3/v2/items/binary_frame.rs
- lofty/src/id3/v2/items/encapsulated_object.rs
- lofty/src/id3/v2/items/event_timing_codes_frame.rs
- lofty/src/id3/v2/items/extended_text_frame.rs
- lofty/src/id3/v2/items/extended_url_frame.rs
- lofty/src/id3/v2/items/key_value_frame.rs
- lofty/src/id3/v2/items/language_frame.rs
- lofty/src/id3/v2/items/ownership_frame.rs
- lofty/src/id3/v2/items/popularimeter.rs
- lofty/src/id3/v2/items/private_frame.rs
- lofty/src/id3/v2/items/relative_volume_adjustment_frame.rs
- lofty/src/id3/v2/items/sync_text.rs
- lofty/src/id3/v2/items/text_information_frame.rs
- lofty/src/id3/v2/items/timestamp_frame.rs
- lofty/src/id3/v2/items/unique_file_identifier.rs
- lofty/src/id3/v2/items/url_link_frame.rs
- lofty/src/id3/v2/tag.rs
- lofty/src/id3/v2/tag/tests.rs
Rustfmt was starting to struggle with the level of indentation previously.
Everything is now in a single `match` statement. Also took the opportunity to remove the generic conversion of POPM frames.
> ID3v2: Cleanup `SplitTag` impl

- CHANGELOG.md
- lofty/src/id3/v2/frame/conversion.rs
- lofty/src/id3/v2/tag.rs
- lofty/src/id3/v2/tag/tests.rs
- lofty/src/tag/item.rs
As mentioned in the TODO, this is a temporary hack that doesn't allow any 4 character TXXX/WXXX descriptions. A better solution in the future would be to have the `ItemKey` map entries be prefixed.
So rather than:
`"REPLAYGAIN_ALBUM_GAIN" => ReplayGainAlbumGain`
It'd be:
`"TXXX:REPLAYGAIN_ALBUM_GAIN" => ReplayGainAlbumGain,`
closes #309
> ID3v2: Disallow 4 character TXXX descriptions as `ItemKey`

- CHANGELOG.md
- lofty/src/mpeg/header.rs
- lofty/src/mpeg/properties.rs
- lofty/src/mpeg/read.rs
- lofty/src/properties/tests.rs
When estimating the duration of an MPEG file using the bitrate, we rely on the offset of the last frame in the file. Turns out the last frame wasn't being returned, just one that happened to be near the end of the file. This wasn't major, as it just reported durations 100ms or so off.
> MPEG: Improve duration estimation

- CHANGELOG.md
- lofty/src/file/tagged_file.rs
- lofty/tests/files/mpeg.rs
Hey, hello there!
I noticed `BoundTaggedFile` (which takes a file) doesn't have a method to retrieve back the original file handle, so I added a fairly simple and short method to retrieve it back. 
I also added a mp3 test case for it.
> Add into_inner for BoundTaggedFile

- CHANGELOG.md
- lofty/src/mpeg/header.rs
- lofty/src/mpeg/properties.rs
- lofty/src/mpeg/read.rs
For files with a VBR header:
Thanks to @naglis for correcting the length calculation. (issue: #412)
For files without a VBR header:
`rev_search_for_frame_header` would get tripped up on files with trailing data
that looked like a frame sync (ex. 0xFFFF). This would also result in durations that are
slightly off.
For now, VBR streams are still assumed to be CBR. I have not seen a file this does not
work for yet. Eventually it would be nice to have more accurate calculation, but that will require we read the *entire* file.
closes #412
> MPEG: Improve duration calculation

- CHANGELOG.md
- Cargo.toml
- lofty/src/ape/read.rs
- lofty/src/config/parse_options.rs
- lofty/src/config/write_options.rs
- lofty/src/id3/v2/frame/content.rs
- lofty/src/id3/v2/frame/header/mod.rs
- lofty/src/id3/v2/frame/header/parse.rs
- lofty/src/id3/v2/frame/mod.rs
- lofty/src/id3/v2/frame/read.rs
- lofty/src/id3/v2/header.rs
- lofty/src/id3/v2/items/attached_picture_frame.rs
- lofty/src/id3/v2/items/extended_text_frame.rs
- lofty/src/id3/v2/items/extended_url_frame.rs
- lofty/src/id3/v2/items/key_value_frame.rs
- lofty/src/id3/v2/items/language_frame.rs
- lofty/src/id3/v2/items/ownership_frame.rs
- lofty/src/id3/v2/items/text_information_frame.rs
- lofty/src/id3/v2/items/timestamp_frame.rs
- lofty/src/id3/v2/read.rs
- lofty/src/id3/v2/tag.rs
- lofty/src/id3/v2/tag/tests.rs
- lofty/src/id3/v2/write/frame.rs
- lofty/src/id3/v2/write/mod.rs
- lofty/src/util/text.rs
Using `WriteOptions::use_id3v23`, the caller now has the choice to write ID3v2.3 tags, which is necessary for older software.
closes #62
> ID3v2: Support writing ID3v2.3 tags

- lofty/src/id3/v2/items/timestamp_frame.rs
- lofty/src/tag/items/timestamp.rs
I had a file with an empty timestamp frame that errored with `ParsingMode::BestAttempt`. Now that's only an error case with `ParsingMode::Strict`.
> ID3v2: Ignore empty timestamp frames

- lofty/src/tag/item.rs
- lofty/src/tag/mod.rs
The behavior of the `take_string()` and other string accessor methods has changed in lofty v0.20.0. They now return values from all `TagItem`s, regardless of their description. This is unexpected for ID3v2 tags where the description is meaningful. Regular `TagItem`s usually have an empty description.
The new methods are needed to extract only regular `TagItem`s with an empty description from an ID3v2 tag. The example demonstrates how to achieve this for `ItemKey::Comment`.
> Add Tag::take_filter()

- CHANGELOG.md
- lofty/src/flac/write.rs
`PADDING` blocks were incorrectly getting moved to the end of the header without the `Last-metadata-block` getting set.
closes #442
> FLAC: Stop moving padding blocks

- Cargo.toml
- fuzz/Cargo.toml
- fuzz/fuzz_targets/aacfile_read_from.rs
- fuzz/fuzz_targets/aifffile_read_from.rs
- fuzz/fuzz_targets/apefile_read_from.rs
- fuzz/fuzz_targets/filetype_from_buffer.rs
- fuzz/fuzz_targets/flacfile_read_from.rs
- fuzz/fuzz_targets/mp4file_read_from.rs
- fuzz/fuzz_targets/mpcfile_read_from.rs
- fuzz/fuzz_targets/mpegfile_read_from.rs
- fuzz/fuzz_targets/opusfile_read_from.rs
- fuzz/fuzz_targets/picture_from_ape_bytes.rs
- fuzz/fuzz_targets/picture_from_flac_bytes.rs
- fuzz/fuzz_targets/picture_from_reader.rs
- fuzz/fuzz_targets/pictureinformation_from_jpeg.rs
- fuzz/fuzz_targets/pictureinformation_from_png.rs
- fuzz/fuzz_targets/probe_read.rs
- fuzz/fuzz_targets/speexfile_read_from.rs
- fuzz/fuzz_targets/vorbisfile_read_from.rs
- fuzz/fuzz_targets/wavfile_read_from.rs
- fuzz/fuzz_targets/wavpackfile_read_from.rs
None of the fuzz targets have been touched in awhile, so they haven't been compiling for most of the year probably.
`lofty-fuzz` has been added to the workspace, so any future build failures should be caught by CI.
> Fuzz: Make all targets build again

- CHANGELOG.md
- lofty/src/tag/items/timestamp.rs
> Timestamp: Support parsing without separators

- CHANGELOG.md
- lofty/src/id3/v2/tag.rs
- lofty/src/id3/v2/tag/tests.rs
- lofty/src/tag/item.rs
This is a multi-valued item where each entry contains one artist name.
See <https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html#artists>.
> ItemKey: Add `ItemKey::TrackArtists`

- CHANGELOG.md
- lofty/src/id3/v2/items/timestamp_frame.rs
- lofty/src/tag/items/timestamp.rs
> Timestamp: Allow short-circuiting on partially invalid inputs

- lofty/Cargo.toml
- lofty/src/tag/mod.rs
- ogg_pager/CHANGELOG.md
- ogg_pager/src/lib.rs
- ogg_pager/src/paginate.rs
> ogg_pager: Fix writing of perfectly divisible packets

- CHANGELOG.md
- lofty/src/iff/wav/read.rs
- lofty/src/iff/wav/tag/mod.rs
- lofty/src/iff/wav/tag/read.rs
- lofty/src/mp4/ilst/read.rs
> Move some errors to strict mode

- examples/tag_reader.rs
I was just looking at your examples for a personal project of mine and saw that the URL to `ItemKey` was invalid
> update url in tag_reader example to correct url to ItemKey

- lofty/src/ape/tag/mod.rs
I was looking around in the `ApeTag` documentation and found the following to be pointing to invalid locations:
- `ItemValue`
- `ItemValue::Binary`
- `Picture::from_ape_bytes`
- `PictureType::Undefined`
I updated them to point to the right locations and tested it on my machine.
Feel free to let me know if any changes need to be made. :)
> NOTE: This is a duplicate of a previous pull request I made, but with a verified the commit to make GitHub happy.
> Fix references to ItemValue, Picture, and PictureType in ApeTag

- lofty/Cargo.toml
- lofty_attr/src/lofty_tag.rs
This fixes #505
I went an implemented the fix suggested in the said issue.
I also changed referencing `lofty_attr` to use `path` instead of published version in `lofty`, 
If this is not wanted, I can easily revert it.
Let me know if this is good to go!
> Fix File Type References in Supported File Types Section in Tag Documentation

- lofty/src/id3/v2/tag.rs
This should fix #507 
I only added artist, release artist, and work id because I believe that's how [MusicBrainz Picard](https://picard.musicbrainz.org/) maps it, Though I'm not a hundred percent sure. 
Lemme know if there is anything else I can do. :)
> Preserve multiple MusicBrainz artist, release artist, and work id tags when writing in Id3v2

- lofty/src/file/file_type.rs
- lofty/src/picture.rs
Adds two simple quality of life functions to `FileType` and `MimeType`.
```rust
FileType::Mpeg.ext(); // Some("mp3")
MimeType::Jpeg.ext(); // Some("jpg")
```
My use case is that I want to extract the pictures and save them separately to disk, so this saves me a manual pattern match on the extension of the file.
> Add ext functions to file types

- CHANGELOG.md
- lofty/src/mp4/properties.rs
An MP4 file with no `mdat` atom is still a *valid* file, but reading its properties is useless. This is only a hard error in `ParsingMode::Strict` now.
> MP4: Demote missing mdat atom error

- CHANGELOG.md
- lofty/src/mp4/atom_info.rs
If a `free` atom claims to be larger than the remainder of the stream, parsing will simply stop. This will now only be a `SizeMismatch` error in `Strict` mode. Invalid padding is a common issue in all tag formats due to buggy software, so it's better to work around it by default rather than discard the entire stream as invalid.
> MP4: Demote atom size mismatch error for `free`

- CHANGELOG.md
- Cargo.toml
- lofty/src/id3/v2/write/chunk_file.rs
- lofty/src/iff/aiff/read.rs
- lofty/src/iff/aiff/tag.rs
- lofty/src/iff/chunk.rs
- lofty/src/iff/wav/mod.rs
- lofty/src/iff/wav/read.rs
- lofty/src/iff/wav/tag/read.rs
- lofty/src/iff/wav/tag/write.rs
Previously, tags were simply written to the end of the file, but this would break files that have junk data appended.
This allows for files with appended junk data that falls outside of the stream length. This can be caused by buggy software misusing padding.
> WAV: Constrain writer to stream length not file length

- lofty/tests/taglib/test_aiff.rs
- lofty/tests/taglib/test_fileref.rs
- lofty/tests/taglib/test_mpeg.rs
> Tests: Enable more TagLib tests

- CHANGELOG.md
- lofty/src/id3/v2/items/language_frame.rs
- lofty/src/id3/v2/items/sync_text.rs
- lofty/src/util/text.rs
UTF-16 encoded COMM and USLT frames can sometimes have a single BOM. Why do some encoders choose to do that? Who knows.
closes #532
> ID3v2: Support single-BOM COMM/USLT frames

- CHANGELOG.md
- lofty/src/ogg/read.rs
- lofty/src/ogg/tag.rs
- lofty/tests/taglib/test_flac.rs
It is nice working with you.
This is my second contribute to this project.
This PR handle disc `current/total` format in Vorbis Comments like how it handle track `current/total` format.
Should this be handle in a different match block please let me know :).
closes #543
> VorbisComments: Handle disc number field with current/total format
