- examples/tag_reader.rs
Just thought this can help clarify how to read other types of tags in the tag reader example :)
Let me know if this helps
> Add example of reading album artist to tag reader

- CHANGELOG.md
- src/mp4/ilst/read.rs
> MP4: Stop validating flags for `gnre` atom upgrade

- src/tag/item.rs
Please refer to the individual commits why these are useful and needed.
> Extend Vorbis Comment support

- src/mp4/ilst/mod.rs
This is needed for merging tags.
> mp4: Implement IntoIterator for Ilst

- src/ape/tag/mod.rs
- src/id3/v2/tag.rs
- src/iff/wav/tag/mod.rs
- src/mp4/ilst/mod.rs
- src/ogg/tag.rs
- src/ogg/vorbis/mod.rs
- src/tag/mod.rs
> Add more IntoIterator implementations

- CHANGELOG.md
- src/ape/tag/mod.rs
- src/id3/v1/tag.rs
- src/id3/v2/tag.rs
- src/tag/mod.rs
As discussed here: https://github.com/Serial-ATA/lofty-rs/commit/a201ab33f792e3b015555f5e3f0c8802341292c0#r98523617
~~Note: The failing test is unrelated, see #133.~~ Only local tests are affected.
> Remove special case handling of empty string values

- src/ape/tag/mod.rs
- src/id3/v2/tag.rs
- src/iff/wav/tag/mod.rs
- src/mp4/ilst/mod.rs
- src/ogg/tag.rs
- src/tag/mod.rs
...without redundant code and accompanied by tests.
> More robust year parsing without allocations

- CHANGELOG.md
- src/id3/v2/frame/id.rs
- src/id3/v2/frame/mod.rs
- src/id3/v2/tag.rs
- src/id3/v2/write/frame.rs
> ID3v2: Fix conversion of user defined frames when using `Tag` writing interface

- src/id3/v2/frame/id.rs
- src/id3/v2/frame/mod.rs
- src/id3/v2/tag.rs
- src/lib.rs
- src/mp4/atom_info.rs
- src/mp4/ilst/write.rs
- src/ogg/write.rs
> Fix clippy::needless_borrow warnings

- src/mp4/ilst/write.rs
This feature wasn't finished, unsure how it wasn't caught sooner. In its current state it'll panic on most numbers. Guess we just got lucky.
> MP4: Fix integer shrinking

- ogg_pager/Cargo.toml
> ogg-pager: Update byteorder dependency

- src/aac/header.rs
- src/aac/read.rs
- src/ape/read.rs
- src/ape/tag/read.rs
- src/flac/block.rs
- src/flac/read.rs
- src/flac/write.rs
- src/id3/mod.rs
- src/id3/v2/header.rs
- src/id3/v2/read.rs
- src/iff/aiff/properties.rs
- src/iff/aiff/read.rs
- src/iff/aiff/tag.rs
- src/iff/wav/read.rs
- src/iff/wav/tag/write.rs
- src/mp4/ilst/read.rs
- src/mp4/properties.rs
- src/mp4/read.rs
- src/mpeg/properties.rs
- src/mpeg/read.rs
- src/musepack/read.rs
- src/ogg/opus/properties.rs
- src/ogg/read.rs
- src/ogg/speex/properties.rs
- src/ogg/vorbis/properties.rs
- src/probe.rs
We weren't making nearly enough use of logs before. Now we have a lot more warnings for users, and debug/trace outputs for developers.
Even after this PR, the usage of logs will still be pretty low. It'd be nice to have more debug and trace output in the future to save me some time.
> Add more logging

- src/aac/read.rs
- src/id3/v2/items/attached_picture_frame.rs
- src/id3/v2/items/event_timing_codes_frame.rs
- src/id3/v2/tag.rs
- src/lib.rs
- src/mp4/ilst/mod.rs
- src/mp4/properties.rs
- src/mpeg/read.rs
- src/ogg/read.rs
- src/ogg/tag.rs
- src/tag/mod.rs
Reduce exceptions from clippy::pedantic.
> Fix some clippy issues

- ogg_pager/CHANGELOG.md
- ogg_pager/Cargo.toml
> ogg_pager: 0.6.0

- src/tag/item.rs
> Rename `PodcastReleaseDate` to `ReleaseDate`

- src/tag/item.rs
> Rename ItemKey variants to PascalCase

- Cargo.toml
- lofty_attr/Cargo.toml
- lofty_attr/src/attribute.rs
- lofty_attr/src/internal.rs
- lofty_attr/src/lib.rs
- lofty_attr/src/lofty_file.rs
- lofty_attr/src/lofty_tag.rs
- lofty_attr/src/util.rs
For the longest time, `lofty_attr` has been an unreadable, fragile mess that somehow works.
Hopefully after this it'll be easier to work with.
> Rewrite `lofty_attr`

- Cargo.toml
Remove redundant Cargo.toml entry.
> Run cargo-diet

- CHANGELOG.md
- src/ogg/vorbis/properties.rs
> Vorbis: Fix panic with zero-length property reads

- Cargo.toml
- ogg_pager/CHANGELOG.md
- ogg_pager/src/lib.rs
- ogg_pager/src/paginate.rs
- src/ogg/read.rs
> ogg_pager: Fix writing of large packets

- .github/workflows/ci.yml
- Cargo.toml
- benches/create_tag.rs
- benches/read_file.rs
- lofty/Cargo.toml
- lofty/src/lib.rs
- lofty/src/mp4/ilst/write.rs
- lofty_attr/Cargo.toml
- lofty_attr/src/lofty_file.rs
- lofty_attr/src/lofty_tag.rs
- ogg_pager/Cargo.toml
- ogg_pager/src/header.rs
- ogg_pager/src/paginate.rs
> misc: Use workspace lints table

- CHANGELOG.md
- lofty/src/mp4/ilst/write.rs
> MP4: Use all available `free` atoms

- CHANGELOG.md
- lofty/src/error.rs
- lofty/src/id3/v2/frame/content.rs
- lofty/src/id3/v2/frame/mod.rs
- lofty/src/id3/v2/items/mod.rs
- lofty/src/id3/v2/items/timestamp_frame.rs
- lofty/src/id3/v2/tag.rs
- lofty/src/id3/v2/tag/tests.rs
- lofty/src/id3/v2/write/frame.rs
- lofty/src/tag/items/mod.rs
- lofty/src/tag/items/timestamp.rs
- lofty/src/tag/mod.rs
> ID3v2: Parse timestamp frames

- CHANGELOG.md
- lofty/src/aac/read.rs
- lofty/src/ape/read.rs
- lofty/src/ape/tag/mod.rs
- lofty/src/ape/tag/read.rs
- lofty/src/ape/tag/write.rs
- lofty/src/config/parse_options.rs
- lofty/src/flac/block.rs
- lofty/src/flac/read.rs
- lofty/src/flac/write.rs
- lofty/src/id3/v2/frame/read.rs
- lofty/src/id3/v2/read.rs
- lofty/src/id3/v2/tag.rs
- lofty/src/id3/v2/tag/tests.rs
- lofty/src/iff/aiff/read.rs
- lofty/src/iff/chunk.rs
- lofty/src/iff/wav/read.rs
- lofty/src/mp4/ilst/mod.rs
- lofty/src/mp4/ilst/read.rs
- lofty/src/mp4/moov.rs
- lofty/src/mp4/properties.rs
- lofty/src/mpeg/read.rs
- lofty/src/musepack/read.rs
- lofty/src/ogg/read.rs
- lofty/src/ogg/tag.rs
- lofty/src/wavpack/read.rs
> ParseOptions: Add read_cover_art

- lofty/src/id3/v2/read.rs
- lofty/src/id3/v2/tag.rs
- lofty/src/id3/v2/tag/tests.rs
- lofty/src/id3/v2/write/frame.rs
* TDAT is DDMM, was previously written as MMDD
* TCON conversion will properly handle refinements
* TIPL and TMCL are now merged into IPLS
> ID3v2.3: Fix some writing issues

- CHANGELOG.md
- lofty/src/mp4/ilst/read.rs
- lofty/src/mp4/ilst/write.rs
> MP4: Support reading any size flag atom
